#sbt "run _int.data 0.8 18dt[maxDepth=5]"
#sbt "run yeast_discrete.txt 0.8 200nb"
#sbt "run yeast_discrete.txt 0.8 2dt[maxDepth=6]"
#sbt "run yeast_discrete.txt 0.8 20dt[maxDepth=6]"
#sbt "run haberman.arff 0.8 901dt[maxDepth=1]"
#sbt "run letter-recognition.txt 0.8 100dt[maxDepth=6]"
# http://www.csie.ntu.edu.tw/~cjlin/libsvmtools/datasets/binary/a9a
#sbt "run a9a 0.9 dt"
#sbt "run glass_discretized.arff 0.9 dt[maxDepth=1]"
#sbt "run glass_discretized.arff 0.9 dt[maxDepth=1]"
#sbt "run glass_discretized.arff 0.9 100dt[maxDepth=1]"
sbt "run glass_discretized.arff 0.9 100nb"
#sbt "run glass_discretized.arff 0.9 480dt[maxDepth=1]"
#sbt "run glass_discretized.arff 0.9 dt"
